### PR TITLE
Add initial project owners document

### PR DESCRIPTION
**Pull request by scott-wilson**
Add the initial project owners document. Once we approve this, we should update the contributors document in the projects.

### CODE REVIEW

**Comment by davvid** [comment]
+1 from me. Should we submit PRs adding our names once this is merged?

**Comment by scott-wilson** [comment]
> +1 from me. Should we submit PRs adding our names once this is merged?

We can, or just put your name here and I'll add it to the PR.

**Comment by davvid** [comment]
Ptex: David Aguilar (primary), TBD secondary

**Comment by gsakura** [comment]
> Ptex: David Aguilar (primary), TBD secondary

Hello, adding myself (Garret Sakura) as secondary

**Comment by justint** [comment]
> > Ptex: David Aguilar (primary), TBD secondary
> 
> Hello, adding myself (Garret Sakura) as secondary

Hello! 👋🏻 Also adding myself (Justin Tennant) as a secondary.

**Comment by scott-wilson** [comment]
@gsakura @justint, thanks for volunteering as a secondary. Which project would you like to be a secondary for? We are currently having a max of one secondary per project.

**Comment by davvid** [comment]
Thanks @scott-wilson and team for meeting up yesterday. We met amongst ourselves today and we've decided on myself and @gsakura for ptex-bind. All three of us will have maintainer access to the repo.

**Pull request merged**
