### PR TITLE
Add group policies documentation

### PR DESCRIPTION
**Pull request by scott-wilson**
This is currently incomplete. There's probably more policies documentation that I should write up, but I can't think of any at the moment.

### CODE REVIEW

**Comment by anderslanglands** [comment]
CoC is a great place to start! Might be good to add our emails and/or a note pointing to the ASWF slack #rust as the main channel as the main place for discussion right now to the landing page.

Would also be nice to have a short blurb on the landing page describing the overall goals for the project ("provide C and Rust bindings for the following VFX libraries:...")

**Comment by anderslanglands** [comment]
The other thing will be a CLA I guess? Eventually?

**Comment by scott-wilson** [comment]
On the todo list!

Also, I haven't thought about the CLA too much asides from telling people that they essentially have to sign two CLAs (ours, and the wrapped libraries').

Asides from that, I'm tempted to say something along the lines of "unless said otherwise, ASWF policies are the ones to follow" since we use their resources.

**Comment by anderslanglands** [comment]
Yep that sounds good to me

**Comment by scott-wilson** [comment]
I'm going to revise the PR with the following:

- Say we don't require a CLA (but things we wrap do).
- Add a creative commons license

If there's nothing else to add, then I'll call this ready to merge.

**Comment by scott-wilson** [comment]
Alright, I think I'm ready to merge. @anderslanglands @meshula @boredstiff @KarthikRIyer Is there anything you think needs to be added to the policies branch before going forward? Or should we call this ready to merge?

**Review by meshula — APPROVED** [review]
Looks good to me!

**Review by KarthikRIyer — APPROVED** [review]

**Pull request merged**
